### ISSUE TITLE
Error with setup.py on iOS 

### ISSUE THREAD

**Issue by The-SamminAter** [BinaryDefense/artillery#102]
I’m running iOS 13.2.3, jailbroken with unc0ver. I have Python 3.7 installed, and have downloaded the whole repository. When I try to run setup.py, I get this message:
```
Traceback (most recent call last):               
  File "./setup.py", line 6, in <module>         
    import time                                  
ImportError: dynamic module does not define init function (inittime)
```

**Comment by russhaun** [comment]
i do not have a jail-broken phone to test for u on this issue. this repo has Py2 & Py3 code mingling together.from my limited research i have found a few things.  Please try and run strictly with py3 to see what happens. Seems this might happen in certain circumstances where if py2 is available it will use it instead. this is just a first step to see if issue can be fixed

**Comment by The-SamminAter** [comment]
Here is what I get: 
```
mobile$ python3 ./setup.py                                  
                                                 
Welcome to the Artillery installer. Artillery is a honeypot, file monitoring, and overall security tool used to protect your nix systems.            
                                                 
Written by: Dave Kennedy (ReL1K)                 
                                                 
Do you want to install Artillery and have it automatically run when you restart [y/n]: y           
[*] Beginning installation. This should only take
a moment.                                        
Traceback (most recent call last):               
  File "./setup.py", line 101, in <module>       
    os.makedirs("/var/artillery_check_root")     
  File "/usr/lib/python3.7/os.py", line 221, in makedirs                                           
    mkdir(name, mode)                            
PermissionError: [Errno 13] Permission denied: '/var/artillery_check_root'
```
Should I be running this with sudo or root?

**Comment by russhaun** [comment]
this project requires root access. im gonna guess thats your issue. try to run it as root. sudo should also work i have a ver on pi3b+ sudo is needed to launch it

**Comment by The-SamminAter** [comment]
I got a bit further this time:
```
Receiving objects: 100% (2017/2017), 1.99 MiB | 3.81 MiB/s, done.                                  
Resolving deltas: 100% (1024/1024), done.        
[*] Finished. If you want to update Artillery go to /var/artillery and type 'git pull'             
[*] Creating com.artillery.plist in your Daemons directory                                         
[*] Adding right permissions                     
Traceback (most recent call last):               
  File "./setup.py", line 172, in <module>       
    check_config()                               
  File "/private/var/mobile/Library/Jailbreakappstbdp/artillery/src/core.py", line 225, in check_config                                              
    configpath = get_config_path()               
  File "/private/var/mobile/Library/Jailbreakappstbdp/artillery/src/core.py", line 266, in get_config_path                                           
    path = globals.g_configfile                  
AttributeError: module 'src.globals' has no attribute 'g_configfile'   
```

**Comment by russhaun** [comment]
not sure why that func is even being used there . comment out the check_config func for now and rerun setup

**Comment by The-SamminAter** [comment]
I have done that, and finished the install, except there’s no `config` file at `/var/artillery`

**Comment by russhaun** [comment]
right it seems to not be picking up the globals file. can u start artillery? it should create one for u

**Comment by russhaun** [comment]
it could be an issue with platform detection too. is there anyway u could do a uname -a for some info?

**Comment by russhaun** [comment]
if your issue is resolved please comment back and let me know . thank u

**Comment by The-SamminAter** [comment]
Sorry about that.
Here is the output of uname -a: `Darwin (phone name) 19.0.0 Darwin Kernel Version 19.0.0: Wed Oct  9 22:42:11 PDT 2019; root:xnu-6153.42.1~1/RELEASE_ARM64_T8020 iPhone11,2 arm64 D321AP Darwin`
Also, this is the error I get when I run artillery.py as root: 
```
Traceback (most recent call last):               
  File "./artillery.py", line 28, in <module>    
    if not os.path.isfile(src.globals.g_appfile):
AttributeError: module 'src.globals' has no attribute 'g_appfile'                                  
```

**Comment by The-SamminAter** [comment]
When I run it, I have to run it by using `python3 filename.py` even though I only have python 3.7 installed.

**Comment by russhaun** [comment]
definitely looks like a detection issue it fails right after the init_globals() func. i will make a branch to make some small changes to see what it is finding. i will post a link when it is ready.

**Comment by russhaun** [comment]
here is a link to a small change to see what platform were running on. this will fail i know that. what i am looking for is what gets printed out.pretty sure i know what the issue is this is just to confirm hopefully:). Replace artillery.py with the one from my branch and run it. post a read out of what it says


https://github.com/russhaun/artillery/tree/ios_check_fix

**Comment by The-SamminAter** [comment]
Here’s the output from running it:
```
/var/artillery root# python3 ./artillery.py                                               
[*] The detected platform was....:darwin         
Traceback (most recent call last):               
  File "./artillery.py", line 30, in <module>    
    if not os.path.isfile(src.globals.g_appfile):
AttributeError: module 'src.globals' has no attribute 'g_appfile'
```

**Comment by russhaun** [comment]
added some more checks to artillery.py download it again from my branch and run it to see what we get.post back the results

**Comment by The-SamminAter** [comment]
Here’s what I get now:
```
/var/artillery root# python3 ./artillery.py                                               
[*] sys.path returns.....                        
/private/var/artillery                           
/usr/lib/python37.zip                            
/usr/lib/python3.7                               
/usr/lib/python3.7/lib-dynload                   
/usr/lib/python3.7/site-packages                 
[*] os.name returns.....:posix                   
[*] sys.platform returns.....:darwin             
Traceback (most recent call last):               
  File "./artillery.py", line 45, in <module>    
    print(f"[*] Executable path...:{src.globals.g_appfile}")                                       
AttributeError: module 'src.globals' has no attribute 'g_appfile'
```

**Comment by russhaun** [comment]
just pushed some more changes please overwrite the following 2 files. artillery.py and core.py with the ones from my repo .core.py is located in the src folder of main artillery install. Post back results when u can

**Comment by The-SamminAter** [comment]
This is the output I get now:
```
/var/artillery root# python3 ./artillery.py                                               
[*] sys.path returns.....                        
/private/var/artillery                           
/usr/lib/python37.zip                            
/usr/lib/python3.7                               
/usr/lib/python3.7/lib-dynload                   
/usr/lib/python3.7/site-packages                 
[*] os.name returns.....:posix                   
[*] sys.platform returns.....:darwin             
[*] Setting global vars.....                     
Press the <ENTER> key to continue... 
```

**Comment by russhaun** [comment]
i made some changes to core.py to reflect your directory setup. overwrite it and rerun it

**Comment by The-SamminAter** [comment]
Done, I get the exact same output as before.

I don’t know if this is important or not, but I still don’t have a config file.

**Comment by russhaun** [comment]
hold on

**Comment by russhaun** [comment]
u have to replace artillery.py & core.py to see my changes

**Comment by russhaun** [comment]
u should see something like this
![output](https://user-images.githubusercontent.com/20805369/90947462-19ad2080-e404-11ea-8f34-b1c146fa0946.png)

**Comment by russhaun** [comment]
its failing on the import somewhere. think it might have a little to do with the fact that this is a nontraditional setup for artillery. it looks in certain paths for stuff. your paths are different. well figure it out

**Comment by russhaun** [comment]
after reading up on this a bit seems likely this is specific to ios?. still trying to see why it is not picking up the globals file. artillery is in your path an so is python.It properly detects what it is running on it finds 'darwin' and 'posix' which is correct. It successfully installed all the files. minus the omission of check_config() func to get through setup. so the only file u are missing should be the config file right? cause it should work from what i see. its just being difficult.

so with this error:
AttributeError: module 'src.globals' has no attribute 'g_appfile' 

artillery.py is actually not finding itself if that makes sense?gonna research this a bit more. Gonna be something silly in the end thanks apple. if u havent already update those 2 files and tell me what u see.

**Comment by russhaun** [comment]
just sent out a msg to the creator of the init_globals() routine to see if he can jump in and get another set of eyes on this. just waiting on a ping back from him. His name is @corelanc0d3r u can find him in the insights->network tab of main repo.

**Comment by russhaun** [comment]
if u can overwrite artillery.py with my copy and tell me what u get.

**Comment by russhaun** [comment]
after running the updated file u should see something like to this


![systemchecks](https://user-images.githubusercontent.com/20805369/90962639-7b5ea080-e47f-11ea-8ef3-42dc52d1055b.png)

**Comment by russhaun** [comment]
just some updates. i added a few checks to try and nail this issue down for u. as u can see i check the import find the globals file and verify the main artillery path. and cleaned up output to be cleaner. same 2 files to copy artillery.py& core.py. try it lmk

![updatedchecks](https://user-images.githubusercontent.com/20805369/90964288-435e5a00-e48d-11ea-914b-12609de69e82.png)

**Comment by The-SamminAter** [comment]
I'll try now

**Comment by The-SamminAter** [comment]
Here's the output I get now:
```
/var/artillery root# python3 ./artillery.py
[*] Trying to import globals file.....
[*] import Sucessful.....
[*] Dumping detailed system info.....
====================Python info==============================
[*] INFO.....:default
[*] INFO.....:May  8 2019 14:19:08
====================Path Info===============================
[*] sys.path returns.....
/private/var/artillery
/usr/lib/python37.zip
/usr/lib/python3.7
/usr/lib/python3.7/lib-dynload
/usr/lib/python3.7/site-packages
====================Uname info==============================
[*] INFO.....:Darwin
[*] INFO.....:iPhone-2
[*] INFO.....:19.0.0
[*] INFO.....:Darwin Kernel Version 19.0.0: Wed Oct  9 22:42:11 PDT 2019; root:xnu-6153.42.1~1/RELEASE_ARM64_T8020
[*] INFO.....:iPhone11,2
[*] INFO.....:arm64
====================Architecure info==============================
[*] INFO.....:64bit
[*] INFO.....:
[*] is_windows() result.....:posix
[*] sys.platform result.....:darwin
=======================Globals Info===============================
[*] Setting global vars.....
[*] Printing out g_appfile location.....None
Press the <ENTER> key to continue...
```

**Comment by The-SamminAter** [comment]
Thanks for your work on this!

**Comment by russhaun** [comment]
np im trying. thanks for letting me try to help. yeah its not finding the globals file. small change to artillery.py. i have 2 checks for globals.py. one for "/public/var/artillery/src/globals.py" and the other in "/var/artillery/src/globals.py". it seems ios symlinks /public with /var. i think my issue is here, just added some print statements to tell me which function im in and also prints error on file not found. just overwrite artillery.py


edit changed the paths they were written wrong

**Comment by The-SamminAter** [comment]
Would you like me to get you more output? I can also get you the python3.7 deb for iOS.

**Comment by russhaun** [comment]
sure if u can. no thats ok like i said i don't have an iPhone. im working from windows for now im stuck @ 3.6.6 close enough so far. appreciate the offer though. just overwrite artillery.py and lmk

**Comment by russhaun** [comment]
commented out some functions as i have that info now. added a check on folder perms to see how its setup. added some print statements inside init_globals() to tell me where it is trying to set global vars at. overwrite artillery.py & core.py to see my changes. lmk when u can

**Comment by russhaun** [comment]
updated a bit u should get something like this plus u should see info on perms

![globalsprintout](https://user-images.githubusercontent.com/20805369/90996764-bb13ae00-e58d-11ea-8703-aa315ddc7864.png)

**Comment by The-SamminAter** [comment]
I get this error now:
```
/var/artillery root# ./artillery.py
  File "./artillery.py", line 49
    print(f"[*] Main script running from.....{HOMEDIR}")
                                                      ^
SyntaxError: invalid syntax
```

**Comment by russhaun** [comment]
try it now

**Comment by The-SamminAter** [comment]
I'm getting the same error. 

Because of the possibility that how I'm updating (artillery and core) may be problematic (without me being aware of that), here's how I'm doing it: 
`rm ./artillery.py; curl https://raw.githubusercontent.com/russhaun/artillery/ios_check_fix/artillery.py >> artillery.py; chmod 0755 artillery.py; rm src/core.py; curl https://raw.githubusercontent.com/russhaun/artillery/ios_check_fix/src/core.py >> src/core.py; chmod 0755 src/core.py; rm ./config; curl https://raw.githubusercontent.com/russhaun/artillery/ios_check_fix/config.txt >> config; chmod 0755 config; python3 ./artillery.py`

**Comment by russhaun** [comment]
looks fine from here .commented that part out for now. just grab artillery.py

**Comment by The-SamminAter** [comment]
I'm getting a new error now:
```
/var/artillery root# ./artillery.py
  File "./artillery.py", line 54
    print(f"===================={HOMEDIR} permissions===============================")
                                                                                    ^
SyntaxError: invalid syntax
```

**Comment by russhaun** [comment]
im a dumb ass bro i forgot something hold on a min. i forgot to add the linux side of that new code

**Comment by russhaun** [comment]
sorry bout that got as little ahead of my self. just artillery.py

**Comment by The-SamminAter** [comment]
I'm getting the same error.

**Comment by russhaun** [comment]
fixed it not sure why its failing on fomat strings. took them out so hopefully it can finish

**Comment by russhaun** [comment]
if it fails on one again i will have to go through and change any strings. gonna take a min. i'll let u know when its done if thats the case

**Comment by russhaun** [comment]
ok well i went through and removed all format strings. try again this time artillery.py & core.py

**Comment by The-SamminAter** [comment]
Here's the output I get:
```
[*] Trying to import globals file.....
[*] import Sucessful.....
[*] Values from pythons built-in globals function at start of script.....
[*] nt detected.....
[*] Dumping detailed system info.....
==========================Globals file=============================
[*] globals file was not found.....:
[*] path looked for.....:/public/var/artillery/src/globals.py
=======================Globals Info===============================
[*] Setting global vars.....
============================================================
[*] Printing out g_appfile location.....None
===================globals imports============================
[*] Values from Artillery imports in __main__
============================================================================
['Formatter', 'MIMEBase', 'MIMEMultipart', 'MIMEText', 'Template', '__annotations__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'addressInNetwork', 'ascii_letters', 'ascii_lowercase', 'ascii_uppercase', 'ban', 'bin2ip', 'capwords', 'check_banlist_path', 'check_config', 'cleanup_artillery', 'config_exists', 'convert_to_classc', 'create_config', 'create_empty_file', 'create_iptables_subset', 'datetime', 'dec2bin', 'digits', 'dir_perm', 'encoders', 'execOScmd', 'execOScmdAsync', 'format_ips', 'formatdate', 'get_config_path', 'get_path', 'get_platform', 'get_sublists', 'gethostname', 'globals', 'grab_time', 'hexdigits', 'id_generator', 'ig', 'import_globals', 'init_globals', 'ip2bin', 'isUserAdmin', 'is_already_banned', 'is_config_enabled', 'is_posix', 'is_valid_ip', 'is_valid_ipv4', 'is_whitelisted_ip', 'is_windows', 'kill_artillery', 'logging', 'mail', 'main_global_imports', 'octdigits', 'os', 'pause', 'pc', 'platform', 'prep_email', 'printCIDR', 'printable', 'pull_source_feeds', 'punctuation', 'random', 're', 'read_config', 'refresh_log', 'runAsAdmin', 'send_mail', 'shutil', 'signal', 'smtplib', 'socket', 'sort_banlist', 'st', 'string', 'struct', 'subprocess', 'sys', 'syslog', 'test', 'thread', 'threat_server', 'time', 'traceback', 'types', 'update', 'urllib', 'urlopen', 'urlparse', 'warn_the_good_guys', 'whitespace', 'write_banlist_banner', 'write_console', 'write_log']
============================================================================
[*] Values from pythons built-in globals function after init_globals() in artillery.py.....
============================================================================
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__']
============================================================================
[*] Printing Configured globals.....
[*] Installed path.....:/private/var/artillery
[*] Artillery path.....:/private/var/artillery/artillery.py
[*] Config path.....:/private/var/artillery/config
[*] Banlist path.....:/private/var/artillery/banlist.txt
[*] Localbanlist path.....:/private/var/artillery/localbanlist.txt
[*] Globals Done.....
============================================================================
[*] Values from pythons built-in globals function after init_globals() in artillery.py.....
============================================================================
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'g_appfile', 'g_apppath', 'g_banlist', 'g_configfile', 'g_localbanlist']
============================================================================
Press the <ENTER> key to continue...^[[3~
```

**Comment by russhaun** [comment]
ok that looks good.it looks like it picks it up now. i am cleaning things up and hopefully this works for u. this is kind of a hack but i think it might work. just artillery.py this time. lmk how it goes

**Comment by The-SamminAter** [comment]
I'm not sure how to record the output I'm currently getting, within 20 seconds most of it is gone, as Cygwin only shows so much, and terminal emulators on my phone crashed when I tried to run it.

**Comment by The-SamminAter** [comment]
I tried writing the output to a file (with ` echo $(python3 ./artillery,py) >> output.txt`), but python3 told me that the file /var/artillery/artillery.py didn't exist.

**Comment by russhaun** [comment]
it tries to run though right and then crashes? ok thought that might happen but it its progress. does it @ least create the config file now ? u might be able to turn some things off from there .check out the config file and try and run it again. after u lmk if anything changes/worked. I'll try and disable some imports for now just to see if we can get u to a running proccess and then start enabling things from there. sound good?definitely something going on with paths here.

**Comment by russhaun** [comment]
also not sure if thats a typo or copied from term but this command has a comma in it
$(python3 ./artillery,py) >> output.txt)

it should be 'artillery.py' not 'artillery,py'

**Comment by russhaun** [comment]
some things to turn off if u can are as follows
MONITOR="OFF"
SSH_DEFAULT_PORT_CHECK="OFF"
SSH_BRUTE_MONITOR="OFF"
this could be ur issue here it tries to update when u load artillery overwriting all my changes defaults to ON
AUTO_UPDATE="OFF"
could also be the src for issues
ROOT_CHECK="OFF"
this 1 deals with logs default is syslog so change it to file it will create alerts.log in logs dir of artillery
SYSLOG_TYPE="FILE"

**Comment by russhaun** [comment]
if it did create the config file make sure u save a copy somewhere. we can always copy over new settings with it before its run

**Comment by russhaun** [comment]
added a copy of config in repo with all settings turned off that might cause issue. also cleaned up a bit small typo nothing major. just remove .txt extension from the file and u should be good

**Comment by russhaun** [comment]
moved pause() func to right before any imports to see if  it runs up to that point.u should be able to clone entire repo to artillery dir ,rename config.txt to config and see if u can run. lmk

**Comment by The-SamminAter** [comment]
I'm a bit unfamiliar with using command-line git, when I try running `git clone https://github.com/russhaun/artillery/tree/ios_check_fix artillery` I get an error that says `fatal: repository 'https://github.com/russhaun/artillery/tree/ios_check_fix/' not found`.
Am I cloning it the wrong way?

**Comment by russhaun** [comment]
i'm not sure about that? i don't think so. im using gitkraken for git.it resolves fine for me. just copy down artillery.py& core.py  just to be safe. and also grab config.txt and remove the ext. the way u used before worked.

**Comment by The-SamminAter** [comment]
Here's the output I'm receiving now:
```
[*] nt detected.....
[*] Dumping detailed system info.....
==========================Globals file=============================
[*] Found globals file located @.....:/private/var/artillery/src/globals.py
[*] Printing out g_appfile location after trying to manually set...../private/var/artillery/artillery.py
[*] Attempting to start.........
2020-08-25 14:10:11: Checking existing config file '/private/var/artillery/config'
2020-08-25 14:10:12: Artillery has started
2020-08-25 14:10:12: If on Windows Ctrl+C to exit.
2020-08-25 14:10:12: Console logging enabled.
2020-08-25 14:10:12:
2020-08-25 14:10:12: Artillery is running from '/private/var/artillery'
Press the <ENTER> key to continue...
```

**Comment by russhaun** [comment]
ok cool thats good. i'm gonna start moving down and enabling imports to see what fails. and then go from there. just artillery.py

**Comment by The-SamminAter** [comment]
Sorry about the delay, here's what I get now:
```
[*] nt detected.....
[*] Dumping detailed system info.....
==========================Globals file=============================
[*] Found globals file located @.....:/private/var/artillery/src/globals.py
[*] Printing out g_appfile location after trying to manually set...../private/var/artillery/artillery.py
[*] Attempting to start.........
2020-09-15 11:53:55: Checking existing config file '/private/var/artillery/config'
2020-09-15 11:53:55: Artillery has started
2020-09-15 11:53:55: If on Windows Ctrl+C to exit.
2020-09-15 11:53:55: Console logging enabled.
2020-09-15 11:53:55:
2020-09-15 11:53:55: Artillery is running from '/private/var/artillery'
2020-09-15 11:53:57: Creating iptables entries, hold on.
2020-09-15 11:53:57: iptables entries created.
Press the <ENTER> key to continue...
```

**Comment by russhaun** [comment]
hey its me didn't forget. removed pause func should run till the end. just artillery.py and core.py this time. "If" it finishes loading. we can start enabling things 1 by 1 and see what happens.

**Comment by The-SamminAter** [comment]
This is what I currently get when running (until I Ctrl+C it, it just continues to run, but doesn't seem to immediately produce any more text):
```
[!] Results from platform.system() Darwin        
[*] Printing out g_appfile location after trying to manually set...../private/var/artillery/artillery.py                                             
[*] Attempting to start.........                 
2020-10-19 16:26:35: Checking existing config file '/private/var/artillery/config'                 
2020-10-19 16:26:35: Artillery has started       
2020-10-19 16:26:35: If on Windows Ctrl+C to exit.                                                 
2020-10-19 16:26:35: Console logging enabled.    
2020-10-19 16:26:35:                             
2020-10-19 16:26:35: Artillery is running from '/private/var/artillery'                            
2020-10-19 16:26:37: Creating iptables entries, hold on.                                           
2020-10-19 16:26:38: iptables entries created.   
2020-10-19 16:26:38: Launching honeypot.         
2020-10-19 16:26:38: Launching thread to get source feeds, if needed.                              
2020-10-19 16:26:38: All set.                    
2020-10-19 16:26:44: [*] Email alerts are not enabled. please look @ /private/var/artillery/config to enable.
```

**Comment by russhaun** [comment]
thats it u are finished loading the main program with no issues. nice. now to start turning on things and see what we get. i would start with turning on the honeypot piece first. in the config file find the section labeled "honeypot ban" and change it from OFF to ON. then do a port scan against ur phone to see if it works. u should see alerts on screen. post back let me know.

**Comment by russhaun** [comment]
u should see something similar to this:

![portscan_results](https://user-images.githubusercontent.com/20805369/96589898-60f44800-12b3-11eb-8ebc-09421be293d0.png)

**Comment by The-SamminAter** [comment]
Here's the output I get now (I ran a regular scan on it with nmap, after changing `HONEYPOT_BAN` to `ON`):
```
[!] Results from platform.system() Darwin        
[] Printing out g_appfile location after trying to manually set...../private/var/artillery/artillery.py                                             
[] Attempting to start.........                 
2020-11-24 08:57:30: Checking existing config file '/private/var/artillery/config'                 
2020-11-24 08:57:30: Artillery has started       
2020-11-24 08:57:30: If on Windows Ctrl+C to exit.                                                 
2020-11-24 08:57:30: Console logging enabled.    
2020-11-24 08:57:30:                             
2020-11-24 08:57:30: Artillery is running from '/private/var/artillery'                            
2020-11-24 08:57:32: Creating iptables entries, hold on.                                           
2020-11-24 08:57:34:     Mass loading 6496 unique
entries from banlist(s)                          
/bin/sh: iptables: command not found             
/bin/sh: iptables: command not found             
/bin/sh: iptables: command not found             
/bin/sh: iptables: command not found             
/bin/sh: iptables: command not found             
/bin/sh: iptables: command not found             
/bin/sh: iptables: command not found             
/bin/sh: iptables: command not found             
/bin/sh: iptables: command not found             
2020-11-24 08:57:35:     9/9 : Done: Added 6496/6496 entries to iptables chain, thank you for waiting.                                               
2020-11-24 08:57:35: iptables entries created.   
2020-11-24 08:57:35: Launching honeypot.         
2020-11-24 08:57:35: Launching thread to get source feeds, if needed.                              
2020-11-24 08:57:35: All set.                    
2020-11-24 08:57:41: [*] Email alerts are not enabled. please look @ /private/var/artillery/config to enable.
```

Here's what the scan output looks like (the mac has been replaced with Xs):
```
Starting Nmap 7.80 ( https://nmap.org ) at 2020-11-24 09:06 PST
mass_dns: warning: Unable to open /etc/resolv.conf. Try using --system-dns or specify valid servers with --dns-servers
mass_dns: warning: Unable to determine any DNS servers. Reverse DNS is disabled. Try using --system-dns or specify valid servers with --dns-servers
Nmap scan report for 169.254.171.2
Host is up (0.0067s latency).
Not shown: 984 closed ports
PORT      STATE SERVICE
21/tcp    open  ftp
22/tcp    open  ssh
25/tcp    open  smtp
53/tcp    open  domain
110/tcp   open  pop3
1433/tcp  open  ms-sql-s
1723/tcp  open  pptp
5060/tcp  open  sip
5061/tcp  open  sip-tls
5800/tcp  open  vnc-http
5900/tcp  open  vnc
8080/tcp  open  http-proxy
10000/tcp open  snet-sensor-mgmt
16993/tcp open  amt-soap-https
44443/tcp open  coldfusion-auth
62078/tcp open  iphone-sync
MAC Address: XX:XX:XX:XX:XX:XX (Apple)

Nmap done: 1 IP address (1 host up) scanned in 44.75 seconds
```

I've noticed that iptables isn't present, I may look into compiling it on/for my phone

**Comment by russhaun** [comment]
hey just checking to see if u made any progress?

**Comment by The-SamminAter** [comment]
> hey just checking to see if u made any progress?

I'm afraid not. iOS and macOS seem to have pf instead of iptables. Would it be possible to experiment with using pf instead of iptables when the `platform.system()` result is `Darwin`?
