### ISSUE TITLE
AttributeError: 'module' object has no attribute 'g_configfile'

### ISSUE THREAD

**Issue by johnjohnsp1** [BinaryDefense/artillery#88]
Hello, trying new release but getting this error on start:

root@KALI:~/artillery# python setup.py 

Welcome to the Artillery installer. Artillery is a honeypot, file monitoring, and overall security tool used to protect your nix systems.

Written by: Dave Kennedy (ReL1K)

Do you want to install Artillery and have it automatically run when you restart [y/n]: y
[*] Beginning installation. This should only take a moment.
[*] Adding artillery into startup through init scripts..
[*] Triggering update-rc.d on artillery to automatic start...
[*] Do you want to keep Artillery updated? (requires internet) [y/n]: y
[*] Checking out Artillery through github to /var/artillery
Clone in '/var/artillery' in corso...
remote: Enumerating objects: 138, done.
remote: Counting objects: 100% (138/138), done.
remote: Compressing objects: 100% (113/113), done.
remote: Total 1914 (delta 94), reused 62 (delta 25), pack-reused 1776
Ricezione degli oggetti: 100% (1914/1914), 1.97 MiB | 3.41 MiB/s, fatto.
Risoluzione dei delta: 100% (959/959), fatto.
[*] Finished. If you want to update Artillery go to /var/artillery and type 'git pull'
[*] Would you like to start Artillery now? [y/n]: y
Traceback (most recent call last):
  File "setup.py", line 175, in <module>
    check_config()
  File "/root/artillery/src/core.py", line 196, in check_config
    configpath = get_config_path()
  File "/root/artillery/src/core.py", line 237, in get_config_path
    path = globals.g_configfile
AttributeError: 'module' object has no attribute 'g_configfile'
root@KALI:~/artillery# 

any ideas ?

running Linux KALI 5.3.0-kali3-amd64 #1 SMP Debian 5.3.15-1kali1 (2019-12-09) using VMwareFusion (11.5.1) on OS X (Catalina 10.15.2)

thanks

**Comment by corelanc0d3r** [comment]
hopefully https://github.com/BinaryDefense/artillery/pull/89 will fix this issue

**Comment by corelanc0d3r** [comment]
@johnjohnsp1 can you please try again with the latest version?

**Comment by johnjohnsp1** [comment]
confirmed, it's now working properly.
thanks for the fix

as last line I have now:
2020-01-08 09:58:28: A brand new config file '/var/artillery/config' was created. Please review the file, change as needed, and launch artillery (again).

**Comment by johnjohnsp1** [comment]
as much more detailed test once i modify the config file and restart artillery getting:

root@KALI:~/artillery# python setup.py 

Welcome to the Artillery installer. Artillery is a honeypot, file monitoring, and overall security tool used to protect your nix systems.

Written by: Dave Kennedy (ReL1K)

Do you want to install Artillery and have it automatically run when you restart [y/n]: y
[*] Beginning installation. This should only take a moment.
[*] Adding artillery into startup through init scripts..
[*] Triggering update-rc.d on artillery to automatic start...
[*] Do you want to keep Artillery updated? (requires internet) [y/n]: y
[*] Checking out Artillery through github to /var/artillery
Clone in '/var/artillery' in corso...
remote: Enumerating objects: 153, done.
remote: Counting objects: 100% (153/153), done.
remote: Compressing objects: 100% (116/116), done.
remote: Total 1929 (delta 104), reused 77 (delta 37), pack-reused 1776
Ricezione degli oggetti: 100% (1929/1929), 1.97 MiB | 856.00 KiB/s, fatto.
Risoluzione dei delta: 100% (969/969), fatto.
[*] Finished. If you want to update Artillery go to /var/artillery and type 'git pull'
2020-01-08 09:58:28: A brand new config file '/var/artillery/config' was created. Please review the file, change as needed, and launch artillery (again).

thanks

**Comment by johnjohnsp1** [comment]
well that was for the successfull installation, this one when modify the config file:

root@KALI:/var/artillery# vi config 
root@KALI:/var/artillery# python restart_server.py 
'module' object has no attribute 'g_configfile'
[*] 2020-01-08 10:20:18: Restarting Artillery Server...
Traceback (most recent call last):
  File "restart_server.py", line 18, in <module>
    write_log("Restarting the Artillery Server process...",1)
  File "/var/artillery/src/core.py", line 928, in write_log
    syslog(alert, alerttype)
  File "/var/artillery/src/core.py", line 839, in syslog
    type = read_config("SYSLOG_TYPE").lower()
  File "/var/artillery/src/core.py", line 277, in read_config
    path = get_config_path()
  File "/var/artillery/src/core.py", line 258, in get_config_path
    path = globals.g_configfile
AttributeError: 'module' object has no attribute 'g_configfile'
root@KALI:/var/artillery# python restart_server.py 
[*] 2020-01-08 10:20:24: Restarting Artillery Server...
Traceback (most recent call last):
  File "restart_server.py", line 18, in <module>
    write_log("Restarting the Artillery Server process...",1)
  File "/var/artillery/src/core.py", line 928, in write_log
    syslog(alert, alerttype)
  File "/var/artillery/src/core.py", line 839, in syslog
    type = read_config("SYSLOG_TYPE").lower()
  File "/var/artillery/src/core.py", line 277, in read_config
    path = get_config_path()
  File "/var/artillery/src/core.py", line 258, in get_config_path
    path = globals.g_configfile
AttributeError: 'module' object has no attribute 'g_configfile'
root@KALI:/var/artillery# 

thanks

**Comment by corelanc0d3r** [comment]
ah - I haven't checked `restart_server.py`
can you see what happens if you simply run `./artillery.py` from the `/var/artillery` folder?

**Comment by johnjohnsp1** [comment]
having this output:

root@KALI:/var/artillery# ./artillery.py 
2020-01-08 12:07:18: Checking existing config file '/var/artillery/config'
2020-01-08 12:07:18: Artillery has started 
2020-01-08 12:07:18: If on Windows Ctrl+C to exit. 
2020-01-08 12:07:18: Console logging enabled.
2020-01-08 12:07:18: 
2020-01-08 12:07:18: Artillery is running from '/var/artillery'
2020-01-08 12:07:18: Running auto update (git pull)
Unhandled exception in thread started by <function update at 0x7fd283e38250>
Traceback (most recent call last):
  File "/var/artillery/src/core.py", line 389, in update
    update = execOScmd("cd %s; git pull" % globals.g_apppath)
  File "/var/artillery/src/core.py", line 570, in execOScmd
    thisline = l.decode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128)
2020-01-08 12:07:20: Creating iptables entries, hold on.
2020-01-08 12:07:20: iptables entries created.
2020-01-08 12:07:20: Activating anti DoS.
2020-01-08 12:07:20: Launching honeypot.
2020-01-08 12:07:20: Launching SSH Bruteforce monitor.
2020-01-08 12:07:21: Launching monitor engines.
2020-01-08 12:07:21: Check system hardening.
2020-01-08 12:07:22: [!] Insecure configuration detected on filesystem: [!] Issue identified: /etc/ssh/sshd_config allows RootLogin. An attacker can gain root access to the system if password is guessed. Recommendation: Change RootLogin yes to RootLogin no
2020-01-08 12:07:22: 
[!] Issue identified: /etc/ssh/sshd_config. SSH is running on the default port 22. An attacker commonly scans for these type of ports. Recommendation: Change the port to something high that doesn't get picked up by typical port scanners.
2020-01-08 12:07:22: 
[!] Issue identified: Password authentication enabled. An attacker may be able to brute force weak passwords.
2020-01-08 12:07:22: 
2020-01-08 12:07:22: 
2020-01-08 12:07:22: Launching email handler.
2020-01-08 12:07:22: Launching thread to get source feeds, if needed.
2020-01-08 12:07:22: All set.

is that correct ?

**Comment by corelanc0d3r** [comment]
looks ok - I'll check out the decode issue, and I was able to reproduce the issue with `restart_server.py`.  Will try to come up with a fix asap

**Comment by johnjohnsp1** [comment]
confirmed, look ok now

root@KALI:/var/artillery# vi config
root@KALI:/var/artillery# python restart_server.py 
[!] 2020-01-08 18:29:16: Killing Old Artillery Process....
[*] 2020-01-08 18:29:16: Restarting Artillery Server...

thanks, appreciate

**Comment by corelanc0d3r** [comment]
cool, feel free to close the issue :)

**Comment by russhaun** [comment]
hey @corelanc0d3r 
       sorry to dig up an old thread but having an issue getting artillery running on a device for someone. issue #102  deals with the globals file. artillery refuses to pick up the system and populate them. littlte background its a jailbroken iphone with py3.7 installed. i've tried a few things and so far nogo. wondering if u could take a look  @ it. more eyes the better. gotta be something silly that im missing.  thanks for your time.
